[project]
name = "python-simple-client-ex"
version = "0.1.0"
description = "simple http client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[dependency-groups]
dev = []
